workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      sdk: openjdk17
    scripts:
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - f20250443@hyderabad.bits-pilani.ac.in